New c8 CI jobs
Change-Id: I3e2369dec315083aa281eea7be4492102963ec13

diff --git a/playbooks/tripleo-ci-reproducer/post.yaml b/playbooks/tripleo-ci-reproducer/post.yaml
--- a/playbooks/tripleo-ci-reproducer/post.yaml
+++ b/playbooks/tripleo-ci-reproducer/post.yaml
@@ -92,6 +92,23 @@
       shell: $(command -v pip || command -v pip3) freeze > pip-user.log
       changed_when: true
 
+    - name: Extract known errors from files
+      shell:
+        grep -a -A4 "syntax error" scheduler.log >> job_errors.txt || true
+        echo "" >> job_errors.txt
+        grep -a "No matching parents" scheduler.log >> job_errors.txt || true
+        echo "" >> job_errors.txt
+        grep -a -A2 "Report change" scheduler.log >> job_errors.txt || true
+        echo "" >> job_errors.txt
+        grep -a -B3 "failed=1" executor.log >> job_errors.txt || true
+        echo "" >> job_errors.txt
+        export build_id=$(grep -a '1001,1' scheduler.log | grep updated | head -1 | grep -Eo " [a-z0-9]+\]" | tr -d " " | tr -d "]")
+        [[ -n "$build_id" ]] && grep -a $build_id scheduler.log > build_id.log
+      args:
+        chdir: "{{ ansible_user_dir }}/tripleo-ci-reproducer"
+      failed_when: false
+      changed_when: true
+
     - name: Copy files from reproducer on node to log
       become: true
       no_log: true
@@ -163,13 +180,12 @@
       ignore_errors: true
       synchronize:
         src: '/usr/share/containers/'
-        dest: '{{ zuul.executor.log_root }}/usr/share/containers/'
+        dest: '{{ zuul.executor.log_root }}/containers-config/'
         mode: pull
         copy_links: true
         verify_host: true
         rsync_opts:
           - "--chown={{ ansible_user }}:{{ ansible_user }}"
-
 
     - name: Copy libvirtd debug log if exists
       become: true
