New c8 CI jobs
Change-Id: I3e2369dec315083aa281eea7be4492102963ec13

diff --git a/playbooks/tripleo-ci-reproducer/post.yaml b/playbooks/tripleo-ci-reproducer/post.yaml
--- a/playbooks/tripleo-ci-reproducer/post.yaml
+++ b/playbooks/tripleo-ci-reproducer/post.yaml
@@ -80,8 +80,9 @@
     - name: Get general system info
       become: true
       shell: |
-        dnf list installed > rpms.log || yum list installed > rpms.log
+        $(command -v dnf || command -v yum) list installed > rpms.log
         free -m > system.log
+        df -h >> system.log
         $(command -v pip || command -v pip3) freeze > pip.log
       args:
         chdir: "{{ ansible_user_dir }}/tripleo-ci-reproducer"
@@ -91,6 +92,30 @@
     - name: Get local pip info
       shell: $(command -v pip || command -v pip3) freeze > pip-user.log
       changed_when: true
+
+    - name: Extract known errors from files
+      shell: |
+        set -o pipefail
+        grep -a -A4 "syntax error" scheduler.log >> job_errors.txt || true
+        echo "" >> job_errors.txt
+        grep -a "No matching parents" scheduler.log >> job_errors.txt || true
+        echo "" >> job_errors.txt
+        grep -a -A2 "Report change" scheduler.log >> job_errors.txt || true
+        echo "" >> job_errors.txt
+        grep -a -B3 "failed=1" executor.log >> job_errors.txt || true
+        echo "" >> job_errors.txt
+        export build_id=$(grep -a '1001,1' scheduler.log | grep updated | head -1 | grep -Eo " [a-z0-9]+\]" | tr -d " " | tr -d "]" || true)
+        grep -a "$build_id" scheduler.log > build_id.log
+        echo "$build_id"
+      args:
+        chdir: "{{ ansible_user_dir }}/tripleo-ci-reproducer"
+      failed_when: false
+      changed_when: true
+      register: build_id
+
+    - name: Print build ID
+      debug:
+        msg: "Build ID is {{ build_id.stdout }}"
 
     - name: Copy files from reproducer on node to log
       become: true
@@ -163,13 +188,12 @@
       ignore_errors: true
       synchronize:
         src: '/usr/share/containers/'
-        dest: '{{ zuul.executor.log_root }}/usr/share/containers/'
+        dest: '{{ zuul.executor.log_root }}/containers-config/'
         mode: pull
         copy_links: true
         verify_host: true
         rsync_opts:
           - "--chown={{ ansible_user }}:{{ ansible_user }}"
-
 
     - name: Copy libvirtd debug log if exists
       become: true
